[package]
name = "maven_plugin"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = { version = "1.4" }
proto_pdk = { version = "0.32" }
rustc-hash = "2.1"
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["wasm"]
wasm = []

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
